name: CD

on:
  workflow_dispatch:

jobs:
  check-code:
    uses: ./.github/workflows/check-code.yml
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/setup-python-uv

      - name: Install Python Dependencies
        run: uv sync --frozen --all-extras

      - name: Run tests
        env:
          WX_API_KEY: ${{ secrets.WX_API_KEY }}
          WX_PROJECT_ID: ${{ secrets.WX_PROJECT_ID }}
          WX_SPACE_ID: ${{ secrets. WX_SPACE_ID }}
          WX_URL: ${{ vars.WX_URL }}
        run: |
          uv run --no-sync pytest -v --cov=. --cov-report=html
