name: Publish to Test PyPI

on:
  workflow_dispatch:
env:
  UV_FROZEN: "1"

permissions:
  contents: read

jobs:
  publish-package-to-testpypi:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/agent-lifecycle-toolkit/
    permissions:
      id-token: write
    steps:
      - name: Download the distribution package
        uses: actions/download-artifact@v5
        with:
          name: distribution-artifacts
          path: dist/
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
