name: Release to PyPI

env:
  UV_FROZEN: "1"
  WX_API_KEY: ${{ secrets.WX_API_KEY }}
  WX_PROJECT_ID: ${{ secrets.WX_PROJECT_ID }}
  WX_SPACE_ID: ${{ secrets. WX_SPACE_ID }}
  WX_URL: ${{ vars.WX_URL }}

on:
  workflow_dispatch:

jobs:
  check-code:
    uses: ./.github/workflows/check-code.yml
  build:
    # FIXME: this should be done in the CD pipeline. We'll upload the files to the
    # github artifacts for releases.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-verson: ['3.10']
    steps:
    - uses: ./.github/actions/setup-python-uv

  release-package-to-testpypi:
    if: startsWith(github.ref, 'refs/tags')
    needs:
      - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/project/agent-lifecycle-toolkit/
    permissions:
      id-token: write
    steps:
      # FIXME: the distributions should come from the tagged releases
      - name: Download all the dists
        uses: actions/download-artifact@v5
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
